---
output: github_document
---

# GITapi - Seven Bridges Homework

## Installation

You can install the development version of GITapi from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("MarkoKazimirovic/GITapi")
```

Library support following functionalities:

-   Token authentication:

```{r authentication}
library(GITapi)
## Account and token made just for testing purposes
jemeljan <- tokenAuthentication(
                     userName = 'jemeljanPugacov',
                        token = "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"
                     )
jemeljan$response
```

-   Listing all repositories which the authenticated user has access to:

```{r listing}
accesibleRepos <- listRepos(x = jemeljan)
accesibleRepos
```

-   Updating Description of some repository:
```{r updateDesc, echo = FALSE}
updateReposDescription(x = accesibleRepos,
                       reposToUpdate = "testingGITapi",
                       newDescription = "SevenBridges task")
jemeljan <- tokenAuthentication(
                     userName = 'jemeljanPugacov',
                        token = "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"
                     )
accesibleRepos <- listRepos(x = jemeljan)
```

```{r updateDescr}
updateReposDescription(x = accesibleRepos,
                       reposToUpdate = "testingGITapi",
                       newDescription = "SevenBridges task")
accesibleRepos

```
